# Generated by Django 5.2.9 on 2025-12-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='department',
            field=models.CharField(choices=[('COM', 'Commercial'), ('IND', 'Industrial'), ('GEN', 'General')], default='GEN', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='level',
            field=models.CharField(choices=[('O', 'Ordinary Level'), ('A', 'Advanced Level')], default='0', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='stream',
            field=models.CharField(choices=[('ARTS', 'General Arts'), ('SCI', 'General Science'), ('NONE', 'N/A')], default='NONE', max_length=4),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(help_text='e.g., Form 1, Upper Sixth', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='core.subject'),
        ),
    ]
