# Generated by Django 5.2.9 on 2025-12-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_classroom_subjects_remove_subject_description_and_more'),
    ]

    operations = [
    ]
