# Generated by Django 5.2.9 on 2025-12-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('down', 'Down Floor'), ('middle', 'Middle Floor'), ('top', 'Top Floor')], max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('floor_password', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
