# Generated by Django 5.2.9 on 2025-12-29 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_switch_departments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='finance_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.floor'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='floor_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_senior_discipline_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stream_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department'),
        ),
    ]
