# Generated by Django 5.2.9 on 2025-12-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_userprofile_can_switch_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(choices=[('first_cycle', 'First Cycle'), ('second_cycle', 'Second Cycle')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('name', 'department')},
        ),
    ]
