# Generated by Django 5.2.9 on 2025-12-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_alter_stream_name_alter_stream_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Vice Principal', 'Vice Principal'), ('Chief of Works', 'Chief of Works'), ('Discipline Master', 'Discipline Master'), ('Senior Discipline Master', 'Senior Discipline Master'), ('Secretary', 'Secretary'), ('Accountant', 'Accountant')], max_length=50),
        ),
    ]
