# Generated by Django 5.2.9 on 2025-12-29 01:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INDUSTRIAL', 'Industrial'), ('GENERAL', 'General'), ('COMMERCIAL', 'Commercial')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('ADVANCED LEVEL', 'Advanced Level'), ('ORDINARY LEVEL', 'Ordinary Level')], default='ORDINARY LEVEL', max_length=20)),
                ('stream', models.CharField(choices=[('ARTS', 'Arts'), ('SCIENCE', 'Science'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('academic_year', models.CharField(max_length=9)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.department')),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='FULL NAMES')),
                ('date_of_birth', models.DateField(help_text="Cannot be today's date", verbose_name='DATE OF BIRTH')),
                ('date_of_admission', models.DateField(default=datetime.date.today, verbose_name='DATE OF ADMISSION')),
                ('parent_guardian_name', models.CharField(blank=True, max_length=200, verbose_name='Parent/Guardian FULL NAME')),
                ('parent_guardian_contact', models.CharField(blank=True, max_length=20, verbose_name='Parent/Guardian CONTACT')),
                ('address', models.TextField(blank=True)),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('level', models.CharField(choices=[('ORDINARY', 'Ordinary Level (Forms 1-5)'), ('ADVANCED', 'Advanced Level (Sixth Form)'), ('BOTH', 'Both Levels')], default='ORDINARY', max_length=10)),
                ('subject_type', models.CharField(choices=[('CORE', 'Core Subject'), ('ELECTIVE', 'Elective Subject')], default='CORE', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.department')),
            ],
            options={
                'ordering': ['department', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='FULL NAMES')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('employment_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('RESIGNED', 'Resigned'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('qualifications', models.TextField(blank=True, help_text='List degrees, certificates, etc.')),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='core.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['teacher_id'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='assigned_classes', to='core.teacher'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('name', 'department', 'level', 'stream', 'academic_year'), name='unique_class_combo'),
        ),
    ]
